---

- hosts: all
  remote_user: root
  become_user: root
  become: true
  roles:
  - role: ansible-role-easybuild

  vars:
    BIOSVERSION: "86e77e81"
    HPC_ENV_PREFIX: "/apps"
    biopet_dir: "/apps/software/Biopet/BIOS-{{ BIOSVERSION }}"
    reference_dir: "/apps/data/bios/Biopet/BIOS-{{ BIOSVERSION }}/"
    GROUP: "bbmri"
    DEFAULT_USER: "vagrant"
    pb_ebconfigs_version: "2.8.6-BBMRI"
    pb_tmp_lfs: "tmp01"
    pb_base: "{{ HPC_GROUP_PREFIX }}/{{ pb_tmp_lfs }}"

  environment:
    BIOPET_CONFIG: '{{ biopet_dir }}/biopet-bios-config.yml'

  tasks:
  - easybuild: easyconfigs="test"

  - group: name={{ GROUP }} state=present

  - user: name=vagrant shell=/bin/bash groups=easybuild,bbmri,vagrant append=yes

  - name: Create groups dir
    file: path={{ HPC_GROUP_PREFIX }} state=directory state=directory owner={{ DEFAULT_USER }} group=vagrant mode=0775 recurse=yes

  - name: Create software dir
    file: path={{ HPC_ENV_PREFIX }}/software state=directory owner=easybuild group=easybuild mode=0775 recurse=yes

  - name: Create data dir
    file: path={{ HPC_ENV_PREFIX }}/data state=directory owner=easybuild group=easybuild mode=0775 recurse=yes

  - name: Create reference_dir dir
    file: path={{ reference_dir }} state=directory owner=easybuild group=easybuild mode=0775 recurse=yes

  - name: Create generatedscripts dir
    file: path={{ pb_base }}/generatedscripts state=directory owner={{ DEFAULT_USER }} group={{ GROUP }} mode=0775 recurse=yes

  - name: Create Samplesheets dir
    file: path={{ pb_base }}/Samplesheets state=directory owner={{ DEFAULT_USER }} group={{ GROUP }} mode=0775 recurse=yes

  - name: Create projects dir
    file: path={{ pb_base }}/projects state=directory owner={{ DEFAULT_USER }} group={{ GROUP }} mode=0775 recurse=yes

  - name: Create logs dir
    file: path={{ pb_base }}/logs state=directory owner={{ DEFAULT_USER }} group={{ GROUP }} mode=0775 recurse=yes

  - name: Create tmp dir
    file: path={{ pb_base }}/tmp state=directory owner={{ DEFAULT_USER }} group={{ GROUP }} mode=0775 recurse=yes

  - name: Create pb_ebconfigs_prefix dir
    file: path={{ pb_ebconfigs_prefix }} state=directory owner=easybuild group=easybuild mode=0775 recurse=yes

  - name: Download Easybuild Configs
    get_url:
      url: "https://github.com/molgenis/easybuild-easyconfigs/releases/download/{{ pb_ebconfigs_version }}/easybuild-easyconfigs-{{ pb_ebconfigs_version }}.tar.gz"
      dest: "{{ easybuild_sources_dir }}/easyconfigs/{{ pb_ebconfigs_version }}.tar.gz"
      mode: 0644
  - name: Extract Easybuild Configs
    unarchive:
      src:  "{{ easybuild_sources_dir }}/easyconfigs/{{ pb_ebconfigs_version }}.tar.gz"
      dest: "{{ easybuild_software_dir }}/easyconfigs"
      remote_src: yes

  - name: Download reference set
    get_url: url="https://barmsijs.lumc.nl/bios/bios-reference-empty.tar.gz" dest="{{ reference_dir }}/bios-reference.tar.gz" owner=easybuild group=easybuild mode=0775 timeout=300

  - name: extract reference set
    command: tar x -C {{ reference_dir }} -f {{ reference_dir }}/bios-reference.tar.gz



  # Copy source files for EB to VM.
  # Download resources manually, and fix scr location if necessary
  - copy: src=~/Downloads/gmp-6.0.0a.tar.bz2  dest=/apps/sources/g/GCC/ owner=easybuild group=easybuild mode=0644
  - copy: src=~/Downloads/mpc-1.0.2.tar.gz  dest=/apps/sources/g/GCC/ owner=easybuild group=easybuild mode=0644
  - copy: src=~/Downloads/gcc-4.9.3.tar.bz2  dest=/apps/sources/g/GCC/ owner=easybuild group=easybuild mode=0644
  - copy: src=~/Downloads/mpfr-3.1.2.tar.gz  dest=/apps/sources/g/GCC/ owner=easybuild group=easybuild mode=0644
  - copy: src=~/Downloads/BBMap_35.69.tar.gz  dest=/apps/sources/b/BBMap/ owner=easybuild group=easybuild mode=0644
  - copy: src=~/Downloads/GenomeAnalysisTK-3.4-0.tar.bz2  dest=/apps/sources/g/GATK/ owner=easybuild group=easybuild mode=0644
  - copy: src=~/Downloads/GenomeAnalysisTK-3.5.tar.bz2  dest=/apps/sources/g/GATK/ owner=easybuild group=easybuild mode=0644
  - copy: src=~/Downloads/jdk-7u80-linux-x64.tar.gz  dest=/apps/sources/j/Java/ owner=easybuild group=easybuild mode=0644
  - copy: src=~/Downloads/jdk-8u45-linux-x64.tar.gz  dest=/apps/sources/j/Java/ owner=easybuild group=easybuild mode=0644
  - copy: src=~/Downloads/bzip2-1.0.6.tar.gz dest=/apps/sources/b/bzip2/ owner=easybuild group=easybuild mode=0644
  - copy: src=~/Downloads/STAR_2.3.0e.zip dest=/apps/sources/s/STAR/ owner=easybuild group=easybuild mode=0644
  - copy: src=~/Downloads/argparse-1.2.1.tar.gz dest=/apps/sources/p/Python/extensions/ owner=easybuild group=easybuild mode=0644
 #- copy: src=~/Downloads/.bashrc dest=/etc/skel/.bashrc owner=root group=root mode=0644  ##TODO: add blockinfile in template

#  - name: Deploy FastQC
#    shell: source /usr/share/lmod/lmod/init/profile && source {{ HPC_ENV_PREFIX }}/modules/modules.bashrc && module load EasyBuild && eb {{ pb_ebconfigs_prefix }}/easybuild-easyconfigs-{{ pb_ebconfigs_version }}/easybuild/easyconfigs/f/FastQC/FastQC-0.10.1-Java-1.7.0_80.eb  --robot --robot-paths="{{ pb_ebconfigs_prefix }}/easybuild-easyconfigs-{{ pb_ebconfigs_version }}/easybuild/easyconfigs/:"
#    become_user: easybuild
#    become: true

  - name: Deploy Biopet
    shell: source /usr/share/lmod/lmod/init/profile && source {{ HPC_ENV_PREFIX }}/modules/modules.bashrc && module load EasyBuild && eb {{ pb_ebconfigs_prefix }}/easybuild-easyconfigs-{{ pb_ebconfigs_version }}/easybuild/easyconfigs/b/Biopet/Biopet-BIOS-86e77e81.eb --robot --robot-paths="{{ pb_ebconfigs_prefix }}/easybuild-easyconfigs-{{ pb_ebconfigs_version }}/easybuild/easyconfigs/:"
    become_user: easybuild
    become: true

  - name: Deploy NGS_RNA
    shell: source /usr/share/lmod/lmod/init/profile && source {{ HPC_ENV_PREFIX }}/modules/modules.bashrc && module load EasyBuild && eb {{ pb_ebconfigs_prefix }}/easybuild-easyconfigs-{{ pb_ebconfigs_version }}/easybuild/easyconfigs/n/NGS_RNA/NGS_RNA-3.2.3.eb --robot --robot-paths="{{ pb_ebconfigs_prefix }}/easybuild-easyconfigs-{{ pb_ebconfigs_version }}/easybuild/easyconfigs/:"
    become_user: easybuild
    become: true
