---

- hosts: all
  #remote_user: DO NOT specify a user here. Specify login name in your ~/.ssh/config instead.
  roles:
  - role: easybuild-install

  tasks:
  #- easybuild: easyconfigs="test"

  #- group: name={{ GROUP }} state=present

  #- user: name=vagrant shell=/bin/bash groups=easybuild,bbmri,vagrant append=yes

  - name: Create user groups dir
    file: path={{ HPC_GROUP_PREFIX }} state=directory state=directory mode=0775 recurse=yes
  
  - name: Create user groups dir
    file: path={{ HPC_GROUP_PREFIX }} state=directory state=directory mode=0775 recurse=yes

  - name: Create user software dir
    file: path={{ HPC_ENV_PREFIX }}/software state=directory mode=0775 recurse=yes

  - name: Create user data dir
    file: path={{ HPC_ENV_PREFIX }}/data state=directory mode=0775 recurse=yes

#  - name: Create user reference_dir dir
#    file: path={{ reference_dir }} state=directory mode=0775 recurse=yes

  - name: Create user generatedscripts dir
    file: path={{ pb_base }}/generatedscripts state=directory mode=0775 recurse=yes

  - name: Create user Samplesheets dir
    file: path={{ pb_base }}/Samplesheets state=directory mode=0775 recurse=yes

  - name: Create user projects dir
    file: path={{ pb_base }}/projects state=directory mode=0775 recurse=yes

  - name: Create user logs dir
    file: path={{ pb_base }}/logs state=directory mode=0775 recurse=yes

  - name: Create user tmp dir
    file: path={{ pb_base }}/tmp state=directory mode=0775 recurse=yes

  - name: Create user pb_ebconfigs_prefix dir
    file: path={{ pb_ebconfigs_prefix }} state=directory mode=0775 recurse=yes

  - name: Download Easybuild Configs
    get_url:
      url: "https://github.com/molgenis/easybuild-easyconfigs/releases/download/{{ pb_ebconfigs_version }}/easybuild-easyconfigs-{{ pb_ebconfigs_version }}.tar.gz"
      dest: "{{ easybuild_sources_dir }}/easyconfigs/{{ pb_ebconfigs_version }}.tar.gz"
      mode: 0644
  - name: Extract Easybuild Configs
    unarchive:
      src:  "{{ easybuild_sources_dir }}/easyconfigs/{{ pb_ebconfigs_version }}-custom.tar.gz"
      dest: "{{ easybuild_software_dir }}/easyconfigs"
      remote_src: yes

  # Copy source files for EB to VM.
  # Download resources manually, and fix scr location if necessary
  - copy: src=~/Downloads/gmp-6.0.0a.tar.bz2  dest={{ HPC_ENV_PREFIX }}/sources/g/GCC/ mode=0644
  - copy: src=~/Downloads/mpc-1.0.2.tar.gz  dest={{ HPC_ENV_PREFIX }}/sources/g/GCC/ mode=0644
  - copy: src=~/Downloads/gcc-4.9.3.tar.bz2  dest={{ HPC_ENV_PREFIX }}/sources/g/GCC/ mode=0644
  - copy: src=~/Downloads/mpfr-3.1.2.tar.gz  dest={{ HPC_ENV_PREFIX }}/sources/g/GCC/ mode=0644
  - copy: src=~/Downloads/GenomeAnalysisTK-3.7.tar.bz2  dest={{ HPC_ENV_PREFIX }}/sources/g/GATK/ mode=0644
  - copy: src=~/Downloads/jdk-8u45-linux-x64.tar.gz  dest={{ HPC_ENV_PREFIX }}/sources/j/Java/ mode=0644
  - copy: src=~/Downloads/bzip2-1.0.6.tar.gz dest={{ HPC_ENV_PREFIX }}/sources/b/bzip2/ mode=0644
  - copy: src=~/Downloads/argparse-1.2.1.tar.gz dest={{ HPC_ENV_PREFIX }}/sources/p/Python/extensions/ mode=0644
 #- copy: src=~/Downloads/.bashrc dest=/etc/skel/.bashrc owner=root group=root mode=0644  ##TODO: add blockinfile in template

#  - name: Deploy FastQC
#    shell: source /usr/share/lmod/lmod/init/profile && source {{ HPC_ENV_PREFIX }}/modules/modules.bashrc && module load EasyBuild && eb {{ pb_ebconfigs_prefix }}/easybuild-easyconfigs-{{ pb_ebconfigs_version }}/easybuild/easyconfigs/f/FastQC/FastQC-0.10.1-Java-1.7.0_80.eb  --robot --robot-paths="{{ pb_ebconfigs_prefix }}/easybuild-easyconfigs-{{ pb_ebconfigs_version }}/easybuild/easyconfigs/:"
#    become_user: easybuild
#    become: true

  - name: Deploy NGS_DNA
    shell: source {{ lmod_prefix }}/init/profile && source {{ HPC_ENV_PREFIX }}/modules/modules.bashrc && module load EasyBuild && eb {{ pb_ebconfigs_prefix }}/easybuild-easyconfigs-{{ pb_ebconfigs_version }}/easybuild/easyconfigs/n/NGS_DNA/NGS_DNA-{{ pb_ngs_dna_version }}.eb --robot --robot-paths="{{ pb_ebconfigs_prefix }}/easybuild-easyconfigs-{{ pb_ebconfigs_version }}/easybuild/easyconfigs/:"
